version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5555:5432'
    volumes: 
      - ./database-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8082:8080
      