// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/google/uuid"
)

type Coin struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Base string    `json:"base"`
}

type Exchange struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Url          string    `json:"url"`
	TickerFormat string    `json:"ticker_format"`
}

type ExchangeCoin struct {
	ID         uuid.UUID `json:"id"`
	CoinID     uuid.UUID `json:"coin_id"`
	ExchangeID uuid.UUID `json:"exchange_id"`
	Name       string    `json:"name"`
	Base       string    `json:"base"`
}

type ExchangeTicker struct {
	ID              uuid.UUID `json:"id"`
	ExchangeID      uuid.UUID `json:"exchange_id"`
	BaseExchCoinID  uuid.UUID `json:"base_exch_coin_id"`
	QuoteExchCoinID uuid.UUID `json:"quote_exch_coin_id"`
}
