// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	InsertCoin(ctx context.Context, arg InsertCoinParams) (uuid.UUID, error)
	InsertCoinExchange(ctx context.Context, arg InsertCoinExchangeParams) error
	InsertTicker(ctx context.Context, arg InsertTickerParams) error
	SelectAllCoins(ctx context.Context) ([]Coin, error)
	SelectExchangeCoinFromCoinID(ctx context.Context, coinID uuid.UUID) ([]SelectExchangeCoinFromCoinIDRow, error)
	SelectExchangeCoinIDFromBase(ctx context.Context, arg SelectExchangeCoinIDFromBaseParams) (uuid.UUID, error)
	SelectExchangeCoins(ctx context.Context) ([]SelectExchangeCoinsRow, error)
	SelectExchangeTickers(ctx context.Context) ([]SelectExchangeTickersRow, error)
	SelectExchanges(ctx context.Context) ([]Exchange, error)
}

var _ Querier = (*Queries)(nil)
